# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

import main
from PyQt5 import QtCore, QtGui, QtWidgets
####Style#######
style_nome_ok = "background-color: rgba(122, 175, 179,1); \n" "border-radius: 5px;"
style_nome_error = "background-color: rgba(122, 175, 179,1); \n" "border-radius: 5px;\n" "border: 2px solid rgb(255,85,127)"
validar_error = "Por favor, preencha o nome do planeta"

class Ui_MainWindow(object):
    def applicar_hab(self):
        esi_value = self.esi.value()
        nome      = self.nome_i.text()
        massa     = self.massa_i.value()
        raio      = self.raio_i.value()
        teq       = self.teq_i.value()
        r_estrela = self.r_estrela_i.value()
        t_estrela = self.t_estrela_I.value()
        distancia = self.distance_i.value()

        if  not nome:
            self.nome_i.setStyleSheet(style_nome_error)
            self.l_nome.setText(validar_error) 

        else:
             info = main.habitalidade(massa,raio,teq,r_estrela,t_estrela,distancia, nome, esi_value)
             habitalidade = "eh habitável" if info[1]== 1 else "Nao eh habitavel"
             self.l_nome.setText(habitalidade)
             self.l_massa.setText(info[0]["HZD"])


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 490)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 400))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-color: rgb(55, 55, 55);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QFrame(self.centralwidget)
        self.top.setMaximumSize(QtCore.QSize(16777215, 45))
        self.top.setStyleSheet("")
        self.top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.top)
        self.frame_3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(130, 143, 153,0.4);\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(30, 1, 3, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_titulo = QtWidgets.QLabel(self.frame_3)
        self.label_titulo.setStyleSheet("color: rgba(200, 200, 200,);")
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.verticalLayout_3.addWidget(self.label_titulo)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.top)
        self.center = QtWidgets.QFrame(self.centralwidget)
        self.center.setStyleSheet("")
        self.center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center.setObjectName("center")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.center)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info = QtWidgets.QFrame(self.center)
        self.info.setMinimumSize(QtCore.QSize(0, 100))
        self.info.setMaximumSize(QtCore.QSize(16777215, 600))
        self.info.setStyleSheet("")
        self.info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info.setObjectName("info")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.info)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.nome = QtWidgets.QFrame(self.info)
        self.nome.setStyleSheet("background-color: rgba(122, 175, 179,0.5);")
        self.nome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nome.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nome.setObjectName("nome")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.nome)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.nome)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setStyleSheet("margin-bottom: 4px;\n"
"background-color: rgba(0.);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.nome_i = QtWidgets.QLineEdit(self.nome)
        self.nome_i.setStyleSheet(style_nome_ok)
        self.nome_i.setObjectName("nome_i")
        self.horizontalLayout_10.addWidget(self.nome_i, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_4.addWidget(self.nome)
        self.massa = QtWidgets.QFrame(self.info)
        self.massa.setStyleSheet("background-color: rgba(122, 175, 179,0.5);")
        self.massa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.massa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.massa.setObjectName("massa")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.massa)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.massa)
        self.label_2.setStyleSheet("background-color: rgba(,0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.massa_i = QtWidgets.QDoubleSpinBox(self.massa)
        self.massa_i.setStyleSheet("")
        self.massa_i.setObjectName("massa_i")
        self.massa_i.setSingleStep(0.01)
        self.massa_i.setMinimum(0.01)
        self.horizontalLayout_3.addWidget(self.massa_i)
        self.verticalLayout_4.addWidget(self.massa)
        self.raio = QtWidgets.QFrame(self.info)
        self.raio.setStyleSheet("background-color: rgba(122, 175, 179,0.5);")
        self.raio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.raio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.raio.setObjectName("raio")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.raio)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.raio)
        self.label_3.setStyleSheet("background-color: rgba(0.5);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.raio_i = QtWidgets.QDoubleSpinBox(self.raio)
        self.raio_i.setObjectName("raio_i")
        self.raio_i.setSingleStep(0.01)
        self.raio_i.setMinimum(0.01)
        self.horizontalLayout_9.addWidget(self.raio_i)
        self.verticalLayout_4.addWidget(self.raio)
        self.teq = QtWidgets.QFrame(self.info)
        self.teq.setStyleSheet("background-color: rgba(122, 175, 179,0.5);")
        self.teq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.teq.setObjectName("teq")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.teq)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.teq)
        self.label_4.setStyleSheet("background-color: rgba(,0.5);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.teq_i = QtWidgets.QSpinBox(self.teq)
        self.teq_i.setObjectName("teq_i")
        self.teq_i.setSingleStep(10)
        self.teq_i.setMaximum(1000000)
        self.teq_i.setMinimum(1)
        self.horizontalLayout_8.addWidget(self.teq_i)
        self.verticalLayout_4.addWidget(self.teq)
        self.distancia = QtWidgets.QFrame(self.info)
        self.distancia.setStyleSheet("background-color: rgba(254, 255, 139,0.5);")
        self.distancia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.distancia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.distancia.setObjectName("distancia")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.distancia)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.distancia)
        self.label_5.setStyleSheet("background-color: rgba(0.5);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.distance_i = QtWidgets.QDoubleSpinBox(self.distancia)
        self.distance_i.setObjectName("distance_i")
        self.distance_i.setSingleStep(0.01)
        self.distance_i.setMinimum(0.01)
        self.horizontalLayout_7.addWidget(self.distance_i)
        self.verticalLayout_4.addWidget(self.distancia)
        self.r_estrela = QtWidgets.QFrame(self.info)
        self.r_estrela.setStyleSheet("background-color: rgba(254, 255, 139,0.5);")
        self.r_estrela.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.r_estrela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.r_estrela.setObjectName("r_estrela")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.r_estrela)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.r_estrela)
        self.label_6.setStyleSheet("background-color: rgba(0.5);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.r_estrela_i = QtWidgets.QDoubleSpinBox(self.r_estrela)
        self.r_estrela_i.setObjectName("r_estrela_i")
        self.r_estrela_i.setSingleStep(0.01)
        self.r_estrela_i.setMaximum(1000000)
        self.r_estrela_i.setMinimum(0.01)
        self.horizontalLayout_6.addWidget(self.r_estrela_i)
        self.verticalLayout_4.addWidget(self.r_estrela)
        self.t_estrela = QtWidgets.QFrame(self.info)
        self.t_estrela.setStyleSheet("background-color: rgba(254, 255, 139,0.5);")
        self.t_estrela.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.t_estrela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.t_estrela.setObjectName("t_estrela")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.t_estrela)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.t_estrela)
        self.label_7.setStyleSheet("background-color: rgba(,0.5);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.t_estrela_I = QtWidgets.QDoubleSpinBox(self.t_estrela)
        self.t_estrela_I.setObjectName("t_estrela_I")
        self.t_estrela_I.setSingleStep(10)
        self.t_estrela_I.setMaximum(1000000)
        self.t_estrela_I.setMinimum(1)
        self.horizontalLayout_5.addWidget(self.t_estrela_I)
        self.verticalLayout_4.addWidget(self.t_estrela)
        self.ESI = QtWidgets.QFrame(self.info)
        self.ESI.setStyleSheet("\n"
"background-color: rgba(122, 175, 179,0.5);")
        self.ESI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ESI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ESI.setObjectName("ESI")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ESI)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.ESI)
        self.label_8.setStyleSheet("background-color: rgba(84, 171, 97,0.0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.esi = QtWidgets.QDoubleSpinBox(self.ESI)
        self.esi.setObjectName("esi")
        self.esi.setSingleStep(0.01)
        self.esi.setMaximum(1)
        self.esi.setMinimum(0.01)
        self.horizontalLayout_4.addWidget(self.esi)
        self.verticalLayout_4.addWidget(self.ESI)
        self.horizontalLayout.addWidget(self.info)
        self.img = QtWidgets.QFrame(self.center)
        self.img.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.img.setStyleSheet("")
        self.img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img.setLineWidth(1)
        self.img.setObjectName("img")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.img)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.img)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("background-color: rgba(130, 143, 153,0.4);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("background-color: rgb();\n"
"border: 0")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.determinar = QtWidgets.QPushButton(self.frame_4)
        self.determinar.setGeometry(QtCore.QRect(10, 20, 97, 33))
        self.determinar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.determinar.setStyleSheet("QPushButton{\n"
"    background-color: rgba(100, 180, 180,0.4);\n"
"    border-radius: 12px;\n"
"    color: rgb(224,224,224);\n"
"    margin-left:5px\n"
"}\n"
"\n"
"QPushButton:hover{background-color: rgba(224, 224, 224,0.5);\n"
"color: rgb(50,50,50);\n"
"}")
        self.determinar.setObjectName("determinar")
        self.verticalLayout_6.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.l_nome = QtWidgets.QLabel(self.frame_2)
        self.l_nome.setStyleSheet("background-color: rgb(0);")
        self.l_nome.setText("")
        self.l_nome.setObjectName("l_nome")
        self.verticalLayout_7.addWidget(self.l_nome)
        self.l_massa = QtWidgets.QLabel(self.frame_2)
        self.l_massa.setStyleSheet("background-color: rgb(0);")
        self.l_massa.setText("")
        self.l_massa.setObjectName("l_massa")
        self.verticalLayout_7.addWidget(self.l_massa)
        self.l_raio = QtWidgets.QLabel(self.frame_2)
        self.l_raio.setStyleSheet("background-color: rgb(0);")
        self.l_raio.setText("")
        self.l_raio.setObjectName("l_raio")
        self.verticalLayout_7.addWidget(self.l_raio)
        self.l_tef = QtWidgets.QLabel(self.frame_2)
        self.l_tef.setStyleSheet("background-color: rgb(0);")
        self.l_tef.setText("")
        self.l_tef.setObjectName("l_tef")
        self.verticalLayout_7.addWidget(self.l_tef)
        self.l_ra_e = QtWidgets.QLabel(self.frame_2)
        self.l_ra_e.setStyleSheet("background-color: rgb(0);")
        self.l_ra_e.setText("")
        self.l_ra_e.setObjectName("l_ra_e")
        self.verticalLayout_7.addWidget(self.l_ra_e)
        self.l_tef_e = QtWidgets.QLabel(self.frame_2)
        self.l_tef_e.setStyleSheet("background-color: rgb(0);")
        self.l_tef_e.setText("")
        self.l_tef_e.setObjectName("l_tef_e")
        self.verticalLayout_7.addWidget(self.l_tef_e)
        self.l_distancia = QtWidgets.QLabel(self.frame_2)
        self.l_distancia.setStyleSheet("background-color: rgb(0);")
        self.l_distancia.setText("")
        self.l_distancia.setObjectName("l_distancia")
        self.verticalLayout_7.addWidget(self.l_distancia)
        self.l_esi = QtWidgets.QLabel(self.frame_2)
        self.l_esi.setStyleSheet("background-color: rgb(0);")
        self.l_esi.setText("")
        self.l_esi.setObjectName("l_esi")
        self.verticalLayout_7.addWidget(self.l_esi)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.img)
        self.verticalLayout.addWidget(self.center)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMinimumSize(QtCore.QSize(0, 30))
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bottom.setAutoFillBackground(False)
        self.bottom.setStyleSheet("background-color: rgba(130, 143, 153,0.4);")
        self.bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.bottom)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgba(235, 239, 242,);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        #################################################
        #funcoes

        self.determinar.clicked.connect(self.applicar_hab)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Determinador de Potencial de habitalidade"))
        self.label.setText(_translate("MainWindow", "Nome:"))
        self.label_2.setText(_translate("MainWindow", "Massa(EU):"))
        self.label_3.setText(_translate("MainWindow", "Raio (EU):"))
        self.label_4.setText(_translate("MainWindow", "Tef(K):"))
        self.label_5.setText(_translate("MainWindow", "Distancia (AU):"))
        self.label_6.setText(_translate("MainWindow", "Raio estelar: "))
        self.label_7.setText(_translate("MainWindow", "Tef estelar:"))
        self.label_8.setText(_translate("MainWindow", "ESI:"))
        self.determinar.setText(_translate("MainWindow", "Determinar"))
        self.label_9.setText(_translate("MainWindow", "Teq = Temperatura efetiva; EU = Earth Units; K= Kelvin; AU = Astronomic Units"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
